#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Feb  5 18:48:06 2017

@author: elizabethsizemore
"""


A=int(input("Enter the mass number:"))
Z=int(input("Enter the atomic number:"))


#constants with units of MeV
a1=15.67
a2= 17.23
a3= 0.75
a4= 93.2

if (A%2==1):
    a5=0
elif (A%2==0) and (Z%2==0):
    a5=12.0
elif (A%2==0) and (Z%2==1):
    a5=-12.0


B=(a1*A)-(a2*(A**(2/3)))-((a3*(Z**2))/(A**(1/3)))-((a4*((A-2*Z)**(2)))/A)-((a5)/(A**(1/2)))


print ('Binding Energy=',B, 'MeV')
print ('Binding Energy per nucleon',(B/A),'MeV')


#Answers provided below


#Enter the mass number:58
#Enter the atomic number:28
#Binding Energy= 490.78425241273493 MeV
#Binding Energy per nucleon 8.46179745539198 MeV


#>>> runfile('/Users/elizabethsizemore/Documents/Computational_Physics/Sizemore_hw2_prob2', wdir='/Users/elizabethsizemore/Documents/Computational_Physics')
#Enter the mass number:59
#Enter the atomic number:28
#Binding Energy= 498.144677545714 MeV
#Binding Energy per nucleon 8.443130127893458 MeV


#>>> runfile('/Users/elizabethsizemore/Documents/Computational_Physics/Sizemore_hw2_prob2', wdir='/Users/elizabethsizemore/Documents/Computational_Physics')
#Enter the mass number:58
#Enter the atomic number:27
#Binding Energy= 485.30934897614435 MeV
#Binding Energy per nucleon 8.367402568554214 MeV
#>>> 